//@ sourceMappingURL=test.map
// Generated by CoffeeScript 1.6.1
(function() {
  var A, B, main,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  A = (function() {

    function A() {
      this.aaa = "123";
    }

    A.prototype.helloA = function() {
      return console.log("HelloA");
    };

    return A;

  })();

  B = (function(_super) {

    __extends(B, _super);

    function B() {
      this.bbb = "234";
      B.__super__.constructor.apply(this, arguments);
      this.aaa = 456;
    }

    B.prototype.helloA = function() {
      return console.log("HelloA form b");
    };

    B.prototype.helloB = function() {
      return console.log("HelloB");
    };

    return B;

  })(A);

  main = function() {
    var a;
    console.log("source map");
    console.log("test");
    a = new B();
    a.helloA();
    return a.helloB();
  };

  main();

}).call(this);
